"""added notify_status

Revision ID: 8af5c8e56ac9
Revises: 9a90e0727887
Create Date: 2025-02-10 02:09:13.207981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af5c8e56ac9'
down_revision: Union[str, None] = '9a90e0727887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('notify_status', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_tasks_notify_status'), 'tasks', ['notify_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_notify_status'), table_name='tasks')
    op.drop_column('tasks', 'notify_status')
    # ### end Alembic commands ###
