"""remove due date and add task status

Revision ID: 9a90e0727887
Revises: daf380571cc6
Create Date: 2025-02-09 00:34:58.096680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a90e0727887'
down_revision: Union[str, None] = 'daf380571cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_index('ix_tasks_due_date', table_name='tasks')
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.create_index('ix_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
