"""initial db

Revision ID: daf380571cc6
Revises: 
Create Date: 2025-02-07 14:38:33.584491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf380571cc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eisenhower_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eisenhower_categories_category'), 'eisenhower_categories', ['category'], unique=False)
    op.create_index(op.f('ix_eisenhower_categories_id'), 'eisenhower_categories', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('notify_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('eisenhower_cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eisenhower_cat_id'], ['eisenhower_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_completed_at'), 'tasks', ['completed_at'], unique=False)
    op.create_index(op.f('ix_tasks_description'), 'tasks', ['description'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_eisenhower_cat_id'), 'tasks', ['eisenhower_cat_id'], unique=False)
    op.create_index(op.f('ix_tasks_estimated_time'), 'tasks', ['estimated_time'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_notify_at'), 'tasks', ['notify_at'], unique=False)
    op.create_index(op.f('ix_tasks_start_date'), 'tasks', ['start_date'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    
    op.execute(
        """
        INSERT INTO eisenhower_categories (category)
        VALUES ('Urgent and Important'),
               ('Not Urgent but Important'),
               ('Urgent but Not Important'),
               ('Not Urgent and Not Important');
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_start_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_notify_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_estimated_time'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_eisenhower_cat_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_description'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_completed_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_eisenhower_categories_id'), table_name='eisenhower_categories')
    op.drop_index(op.f('ix_eisenhower_categories_category'), table_name='eisenhower_categories')
    op.drop_table('eisenhower_categories')
    # ### end Alembic commands ###
